# Generated by Django 2.0.2 on 2018-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_auto_20180611_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='preparation',
            field=models.CharField(max_length=2000),
        ),
    ]
