# Generated by Django 2.2.20 on 2021-10-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('rarity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Effet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarteDresseur',
            fields=[
                ('carte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.Carte')),
            ],
            bases=('cardGame.carte',),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('body', models.BooleanField(default=False)),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetPouvoir', to='cardGame.Effet')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.TextField(blank=True)),
                ('cartes', models.ManyToManyField(to='cardGame.Carte')),
                ('personnage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnage', to='cardGame.Personnage')),
            ],
        ),
        migrations.CreateModel(
            name='Attaque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cout', models.TextField(blank=True)),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetAttaque', to='cardGame.Effet')),
            ],
        ),
        migrations.CreateModel(
            name='CartePokemon',
            fields=[
                ('carte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.Carte')),
                ('pv', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('retreatCost', models.IntegerField(default=0)),
                ('brillant', models.BooleanField(default=False)),
                ('obscur', models.BooleanField(default=False)),
                ('delta', models.BooleanField(default=False)),
                ('ex', models.BooleanField(default=False)),
                ('shiny', models.BooleanField(default=False)),
                ('attaques', models.ManyToManyField(to='cardGame.Attaque')),
                ('pokeBody', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokeBody', to='cardGame.Power')),
                ('pokePower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokePower', to='cardGame.Power')),
                ('resistance', models.ManyToManyField(to='cardGame.Type')),
                ('type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type1', to='cardGame.Type')),
                ('type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type2', to='cardGame.Type')),
                ('weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weakness', to='cardGame.Type')),
            ],
            bases=('cardGame.carte',),
        ),
        migrations.CreateModel(
            name='CarteEnergie',
            fields=[
                ('carte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.Carte')),
                ('base', models.BooleanField(default=True)),
                ('type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='cardGame.Type')),
            ],
            bases=('cardGame.carte',),
        ),
        migrations.CreateModel(
            name='CarteDresseurInstantane',
            fields=[
                ('carte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.Carte')),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetCarteInstantane', to='cardGame.Effet')),
            ],
            bases=('cardGame.carte',),
        ),
        migrations.CreateModel(
            name='CarteSupporter',
            fields=[
                ('cartedresseur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.CarteDresseur')),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetCarteSupporter', to='cardGame.Effet')),
            ],
            bases=('cardGame.cartedresseur',),
        ),
        migrations.CreateModel(
            name='CarteStade',
            fields=[
                ('cartedresseur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.CarteDresseur')),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetCarteStade', to='cardGame.Effet')),
            ],
            bases=('cardGame.cartedresseur',),
        ),
        migrations.CreateModel(
            name='CarteOutilPokemon',
            fields=[
                ('cartedresseur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.CarteDresseur')),
                ('effet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effetCarteOutil', to='cardGame.Effet')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon', to='cardGame.CartePokemon')),
            ],
            bases=('cardGame.cartedresseur',),
        ),
        migrations.CreateModel(
            name='CarteMachineTechnique',
            fields=[
                ('carteoutilpokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardGame.CarteOutilPokemon')),
                ('attaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attaque', to='cardGame.Attaque')),
            ],
            bases=('cardGame.carteoutilpokemon',),
        ),
    ]
