# Generated by Django 2.2.20 on 2021-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attaque',
            name='degats',
            field=models.IntegerField(default=0),
        ),
    ]
